apiVersion: v1
kind: Namespace
metadata:
  name: devpi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: devpi
  namespace: devpi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devpi
  template:
    metadata:
      labels:
        app: devpi
    spec:
      containers:
        - name: devpi
          image: ghcr.io/devpi/devpi:6.12.0
          imagePullPolicy: IfNotPresent
          args:
            - "--serverdir"
            - "/data"
          env:
            - name: DEVPI_SERVERDIR
              value: /data
          ports:
            - containerPort: 3141
              name: http
          volumeMounts:
            - name: data
              mountPath: /data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: devpi-data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: devpi-data
  namespace: devpi
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: devpi
  namespace: devpi
spec:
  selector:
    app: devpi
  ports:
    - protocol: TCP
      port: 3141
      targetPort: http
  type: ClusterIP
