name: CI
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  pytest:
    runs-on: ubuntu-latest
    env:
      working-directory: ./backend
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.6
      uses: actions/setup-python@v1
      with:
        python-version: 3.6
    - name: Install dependencies
      working-directory: ${{env.working-directory}}
      run: |
        python -m pip install --upgrade pip
        pip install .[dev]
    - name: Test with pytest
      working-directory: ${{env.working-directory}}
      run: |
        pip install pytest
        pytest -vv

  flake8:
    runs-on: ubuntu-latest
    env:
      working-directory: ./backend
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.6
        uses: actions/setup-python@v1
        with:
          python-version: 3.6
      - name: Install flake8
        run: |
          pip install flake8 flake8-docstrings
      - name: Lint with flake8
        working-directory: ${{env.working-directory}}
        run: |
          flake8 . --count --show-source --statistics

  prettier:
    runs-on: ubuntu-latest
    env:
      working-directory: ./frontend
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - name: Fetch repository's history
        run: |
          git fetch --no-tags --prune --unshallow
      - name: Install dependencies
        working-directory: ${{env.working-directory}}
        with:
          cmd: yarn install
      - name: Run format:check against master
        working-directory: ${{env.working-directory}}
        with:
          cmd: yarn format -- --check --branch origin/master

  build:
    runs-on: ubuntu-latest
    env:
      working-directory: ./frontend
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - name: Install dependencies
        working-directory: ${{env.working-directory}}
        with:
          cmd: yarn install
      - name: Build extension
        working-directory: ${{env.working-directory}}
        with:
          cmd: yarn build
